name: Preparant per producci贸
run-name: ${{ github.actor }} est pujant l'aplicaci贸 a PROD 
on:
  push:
    branches:
      - main

jobs:
  Pujar-a-produccio-amb-SCP:
    runs-on: ubuntu-latest
    steps:
      - name: Inicio del trabajo
        run: echo "Rubendelacereza est pujant l'aplicaci贸 a PROD "

      - name: Obtenint el codi del repositori
        uses: actions/checkout@v4

      - name: Linting
        run: |
          cd ${{ github.workspace }}
          cd ./web/actions-vue/
          npm install
          npm run lint

      - name: Fin del trabajo
        run: echo "Desplegament a producci贸 finalitzat"

      - run: echo " This job's status is ${{ job.status }}."
