name: Preparant per producci贸
run-name: ${{ github.actor }} est pujant l'aplicaci贸 a PROD 
on:
  push:
    branches:
      - main

jobs:
  Pujar-a-produccio-amb-SCP:
    runs-on: ubuntu-latest
    steps:
      - name: Inicio del trabajo
        run: echo "Rubendelacereza est pujant l'aplicaci贸 a PROD "

      - name: Obtenint el codi del repositori
        uses: actions/checkout@v4

      - name: Linting
        run: |
          cd ${{ github.workspace }}
          echo "Running ESLint" > ./web/last_deploy.txt
          date >> ./web/last_deploy.txt
          cd ./web/actions-vue/
          npm install
          npm run lint

      - name: Construir la aplicaci贸n
        run: |
          cd ${{ github.workspace }}
          cd ./web/actions-vue/
          npm install
          npm run build

      - name: Despliegue a producci贸n
        run: |
          echo "${{ github.actor }} est pujant l'aplicaci贸 a PROD " > ./web/last_deploy.txt
          date >> ./web/last_deploy.txt
          echo "${{ secrets.PROD_KEY }}" > ~/prod_key.pem
          chmod 600 ~/prod_key.pem
          cd ${{ github.workspace }}
          cd ./web/actions-vue/
          scp -r -o stricthostkeychecking=no -o UserKnownHostsFile=/dev/null -i "~/prod_key.pem" ./dist/* ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}:/home/a20rubdelsan/web/a20rubdelsan.daw.inspedralbes.cat/public_html/

      - name: Fin del trabajo
        run: echo "Desplegament a producci贸 finalitzat"

      - run: echo " This job's status is ${{ job.status }}."
