name: Preparant per producci贸
run-name: ${{ github.actor }} est pujant l'aplicaci贸 a PROD 
on:
  push:
    branches:
      - main

jobs:
  Pujar-a-produccio-amb-SCP:
    runs-on: ubuntu-latest
    steps:
      - name: Obtenint el codi del repositori
        uses: actions/checkout@v4

      - name: Ejecutar ESLint
        run: |
          cd ./web/actions-vue/
          npm install
          npm run lint  # Ajusta este comando seg煤n tu configuraci贸n de ESLint

      - name: Construir la aplicaci贸n
        run: |
          cd ./web/actions-vue/
          npm install
          npm run build

      - name: Verificar carpeta dist
        run: |
          cd ./web/actions-vue/
          if [ ! -d ./dist ]; then
            echo "La carpeta 'dist' no existe. Aseg煤rate de que la construcci贸n se realiz贸 correctamente."
            exit 1
          fi

      - name: Despliegue a producci贸n
        run: |
          echo "${{ secrets.PROD_KEY }}" > ~/prod_key.pem
          chmod 600 ~/prod_key.pem
          cd ${{ github.workspace }}
          echo "Action desplegant a produccio" > ./web/last_deploy.txt
          date >> ./web/last_deploy.txt
          cd ./web/actions-vue/
          scp -r -o stricthostkeychecking=no -o UserKnownHostsFile=/dev/null -i "~/prod_key.pem" ./dist/* ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}:/home/a20rubdelsan/web/a20rubdelsan.daw.inspedralbes.cat/public_html/
          
      - run: echo " This job's status is ${{ job.status }}."
